site_name: Rob's Wiki
site_url: https://robmoore-i.github.io
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  toc:
    permalink: true
nav:
  - Home: index.md
  - Work: work.md
  - Reading:
    - reading/articles.md
    - reading/books.md
    - reading/log.md
    - reading/selected-snippets.md
    - reading/videos.md
  - Writing:
    - Gradle:
      - writing/gradle/insider-guidelines.md
      - writing/gradle/intellij-idea.md
      - writing/gradle/kotlin-dsl.md
      - writing/gradle/gradle-monorepo-structure.md
      - writing/gradle/jvms.md
      - writing/gradle/registering-gradle-tasks.md
      - writing/gradle/custom-task-types.md
      - writing/gradle/custom-repositories.md
      - writing/gradle/secure-dependencies.md
      - writing/gradle/downloading-files.md
    - "Software development":
      - writing/software_development/developer-experience.md
      - writing/software_development/reader-experience.md
      - writing/software_development/tests.md
      - writing/software_development/chestertons-traffic-lights.md
      - writing/software_development/governance-is-not-a-quality-strategy.md
    - Documentation:
      - writing/documentation/divio.md
      - writing/documentation/values.md
    - Tutorials:
      - writing/tutorials/migration-this-wiki-to-fly-io.md
      - writing/tutorials/ukkonens-algorithm-for-mortals.md
      - writing/tutorials/unit-testing-for-jenkins-pipeline-libraries.md
