site_name: Rob's Wiki
site_url: https://robmoore-i.github.io
nav:
  - Home: index.md
  - Work: work.md
  - Reading:
    - reading/log.md
    - reading/books.md
theme:
  name: material
  features:
    - navigation.expand
markdown_extensions:
  toc:
    permalink: true
